### Ping
GET http://localhost:3003/ping

### Get Products
GET http://localhost:3003/product

### Get Products
PUT http://localhost:3003/product
Content-Type: application/json

{
  "products":[
    {
      "product_code": 18,
      "sales_price": 222
    },
    {
      "product_code": 16,
      "sales_price": 333
    },
    {
      "product_code": 19,
      "sales_price": 444
    }
    
  ]
}

### Create Order
POST http://localhost:3003/api/orders
Content-Type: application/json

{
  "pizzas":[
    {
      "name": "Margherita",
      "quantity": 10
    },
    {
      "name": "Bufala",
      "quantity": 10
    }
  ]
}

### Get Orders
GET http://localhost:3003/api/orders

###